name: Déploiement site web statique

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ajout crucial pour les permissions

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Déploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Racine du projet à publier
          publish_branch: gh-pages  # Spécifier explicitement la branche cible
